# ----
# Site

title: Chicago Public Library Maker Lab
url: "https://orange-ape.cloudvent.net/"
baseurl:
google_analytics_key:
disqus_shortname:
newsletter_action:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/images/logo.png
description: Chicago Public Library Maker Lab
author:
  name: CPL Maker Lab
  email: makerspace@chipublib.org
  twitter: # twitter username without the @ symbol
social:
  name: Base Template
  links:
    - https://github.com/CloudCannon/base-jekyll-template

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
#  - jekyll-extract-element
#  - jekyll-archives

# This plugin is not on github :-/
# jekyll-archives:
#  enabled: ['categories']

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# Collections are like custom content types.
collections:
  guides:
    output: true
    permalink: /guide/:path/
  topics:    
    output: true
    permalink: /topic/:path/


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "default"
      comments: false
  -
    scope:
      type: "sets"
    values:
      _hide_content: true


# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS
  
type:
  - document
  - how-to
  - video

  
_options:
  content:
    format: p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    removeformat: true
    link: true
    image: true
    blockquote: true
    numberedlist: true
    bulletedlist: true
    code: true
    table: true
    embed: true
