# ----
# Site

title: Chicago Public Library Maker Lab
url: "https://orange-ape.cloudvent.net/"
baseurl:
google_analytics_key:
disqus_shortname:
newsletter_action:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/images/logo.png
description: Chicago Public Library Maker Lab
author:
  name: CPL Maker Lab
  email: makerspace@chipublib.org
  twitter: cplmakerlab
social:
  name: Base Template
  links:
    - https://github.com/CloudCannon/base-jekyll-template

# -----
# Build 

timezone: Etc/UTC

permalink: /:categories/:title/


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
#  - jekyll-extract-element
#  - jekyll-archives

# This plugin is not availabl for Github Pages :-/
# jekyll-archives:
#  enabled: ['categories']

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# Collections are like custom content types.
collections:
  pages:
    output: true
    permalink: /:path/
  guides:
    output: true
    permalink: /guide/:path/
    _singular_name: Guide    

topics:
  - 2D design
  - 3D design
  - 3D printing  
  - Coding
  - Design 
  - Digital security
  - Electronic cutter
  - Electronics
  - Handcraft
  - Lasercutting
  - Milling
  - Sewing
  

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "default"
      comments: false

type:
  - document
  - how-to
  - video

# -----------
# CloudCannon

uploads_dir: "uploads/:categories/:year/:month/:day/:title"

# CloudCannon Explore UI Settings
_explore:
  groups:
    - heading: Pages
      collections:
        - pages
    - heading: How-To Guides
      collections:
        - guides        
    - heading: Blogging
      collections:
        - posts
        - drafts
    - heading: Site Settings
      collections:
        - data

# CloudCannon Source Editor
_source_editor:   
  tab_size: 2
  
# CloudCannon Content Editor 
_options:
  content:
    format: p h2 h3 h4
    bold: true
    italic: true
    link: true    
    image: true
    removeformat: true
    blockquote: true
    numberedlist: true
    bulletedlist: true
    code: true
    table: true
    embed: true
    
# Footer Icons
social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS